### ISSUE TITLE
"Releases" info is out of date

### ISSUE THREAD

**Issue by vadeg** [zalando-nakadi/kanadi#116]
The latest release according to `Releases` tab is `0.3.3` but the latest version available is [0.4.1](https://search.maven.org/artifact/org.zalando/kanadi_2.11/0.4.1/jar).

Could you please update `Releases` tab?

**Comment by mdedetrich** [comment]
Will look into it next week

**Comment by mdedetrich** [comment]
I will fix this when I integrate sbt-release into Kanadi, see https://github.com/zalando-nakadi/kanadi/issues/136
