### ISSUE TITLE
akka-streams-json will move to pekko

### ISSUE THREAD

**Issue by mdedetrich** [zalando-nakadi/kanadi#205]
@gchudnov Since you appear to be maintaining this project I just want to inform you that a library that this project depends on , [akka-streams-json](https://github.com/mdedetrich/akka-streams-json) will have its final release in the next coming weeks at which point I will put it under maintenance due to the Akka license change. At the point of the final release I will fork akka-astreams-json to use Pekko which is an open source fork of Akka and its ecosystem into the Apache Software Foundation (see https://pekko.apache.org/, https://github.com/apache/incubator-pekko and https://lists.apache.org/list.html?dev@pekko.apache.org).

From that point on only the fork (which will be named pekko-streams-circe) will be maintained. If you are willing to continue this project and/or have any additional questions please let me know in the issue.

**Comment by gchudnov** [comment]
Hi @mdedetrich 
Thank you for the information.

Wondering, what is the status of pekko? How far is it from the 1.0 release?

**Comment by mdedetrich** [comment]
> Wondering, what is the status of pekko?

So pekko is still being worked on and active (you can judge from yourself, its all opensource as an Apache project). Our current status is that we are working towards a 1.0 release which can hopefully done in 1-2 months.

**Comment by mdedetrich** [comment]
@gchudnov Just wanted to let you know that akka-streams-json just published its final Akka artifact, `v0.9.0` (see https://github.com/mdedetrich/akka-streams-json/actions/runs/5138518910/jobs/9247977653). After this point I will put the repo into maintenance and fork it into Pekko as previously stated.

Regarding the status for Pekko, a release candidate is planned in around a week (see https://lists.apache.org/list.html?dev@pekko.apache.org) so hopefully a full release won't be far off. Note that snapshots for Pekko are already being published for Scala versions 2.12 all the way to Scala 3 if you want to try it out now.

**Comment by gchudnov** [comment]
got it, thank you for the information!

**Comment by mdedetrich** [comment]
So [pekko-streams-circe](https://github.com/mdedetrich/pekko-streams-circe), i.e. the pekko fork has just been published, see https://github.com/mdedetrich/pekko-streams-circe/actions/runs/5154098667/jobs/9282177842.

So ff you want to go ahead and try migrating the project to Pekko you can use the following snapshot artifacts
pekko: `0.0.0+26669-ec5b6764-SNAPSHOT`
pekko-http: `0.0.0+4411-6fe04045-SNAPSHOT`
pekko-streams-circe: `0.0.0+94-dbf3173f-SNAPSHOT`

You can see the migration guide here https://pekko.apache.org/docs/pekko/current/project/migration-guides.html

**Comment by mdedetrich** [comment]
@gchudnov Apache Pekko Http 1.0.0 has just been released as well as Pekko Streams Circe 1.0.0 (see https://github.com/mdedetrich/pekko-streams-circe/releases/tag/v1.0.0)

**Comment by gchudnov** [comment]
Hi Matthew!

great to hear, 
Thank you very much!

**Comment by mdedetrich** [comment]
Closing this as done
